#Download page: https://www.spigotmc.org/resources/128629/
#Config explanation: https://github.com/BulPlugins/BulChunkBuster/wiki
#Discord to get help: https://discord.gg/JAe62PEaYv

block_buster: beacon
block_buster_name: "&eBulChunkBuster"
block_buster_lore:
  - ""
  - "&aPlace it to BUST the chunk !"
block_buster_check_all: true

block_buster_sneak_confirmation: false
block_buster_chat_confirmation: true

buster_speed: 1
buster_size: 4
buster_sound: EXPLODE
buster_effect: EXPLOSION_HUGE
destroy_block_after_use: true
chance_to_drop_destroyed_block: 10.0

black_list_materials: [bedrock, spawner, chest]
black_list_worlds: [event, exampleNameWorld]

cooldown_for_each_use: 10
server_y_min: 0

#Enable the claim system you want to use, if enabled, players
#Must be in their own claims to place a block buster.
supports:
  factions: false #saberFaction, factionUUID
  griefprevention: false #https://www.spigotmc.org/resources/1884/

messages:
  buster_run: "&eStarting to bust the chunk.."
  buster_end: "&aThe chunk was bust !"
  buster_receive: "&You receive %amount% block buster"
  buster_give: "&aBlock buster was given"
  blacklist_world: "&cYou can't place a block buster in this world"
  cooldown_error: "&cYou have to wait &e%time% seconds &cbefore using again a blockbuster"
  sneak_confirmation_error: "&cYou must sneak while placing the block to activate the buster."

  chat_confirmation: "&eRun ChunkBuster ? "
  chat_confirmation_yes: "&a&lYES"
  chat_confirmation_no: "&c&lNO"
  chat_confirmation_cancel: "&cBuster canceled."
  chat_confirmation_block_error: "&cThe placed chunk buster block was destroyed before confirmation."

  claim_error: "&cYou can place chunk buster only in your own claims."
  no_permission: "&cYou don't have the permission to use blockbuster .."
