block_buster: beacon
block_buster_name: "name"
block_buster_lore:
  - "line"
block_buster_check_all: true

buster_speed: 1
buster_size: 4
buster_sound: EXPLODE
buster_effect: EXPLOSION_HUGE
destroy_block_after_use: true
drop_destroyed_block: false
chance_to_drop_destroyed_block: 10.0

black_list_materials: [bedrock, spawner, chest]
black_list_worlds: [event, exampleNameWorld]
cooldown_for_each_use: 10

messages:
  buster_placed: "&eStarting to bust the chunk.."
  buster_end: "&aThe chunk was bust !"
  buster_receive: "&You receive a block buster"
  buster_give: "&aBlock buster was given"
  blacklist_world: "&cYou can't place a block buster in this world"
  cooldown_error: "&cYou have to wait &e%time% &cbefore using again a blockbuster"
  no_permission: "&cYou don't have the permission to use blockbuster .."
