name: BulChunkBuster
main: com.alihaine.bulchunkbuster.ChunkBuster
version: ${version}
author: AliHaine
api-version: 1.13
commands:
  bulchunkbuster:
    description: Main command
    aliases:
      - bchunkbuster
      - bcb
    permission: bulchunkbuster.admin
    permission-message: You do not have permission!
    usage: /bchunkbuster <player> (optional amount)
  busterconfirmation:
    description: Used to confirm the buster (with chat component)